### ISSUE TITLE
There is an error loading the model

### ISSUE THREAD

**Issue by giovannicampagnolo** [MarlonJD/babylonjs_viewer#11]
When i try to load a .glb model from a web link there is this error:

`Unable to import meshes from /modelLink.glb: Error status: 0`

it only works with this models:

**https://modelviewer.dev/shared-assets/models/NeilArmstrong.glb**
**https://models.babylonjs.com/boombox.glb**

Anyone have the same problem? @MarlonJD @MIGMLG @

**Comment by MarlonJD** [comment]
Which software are you using to export glb? Did you test from here https://sandbox.babylonjs.com/

**Comment by giovannicampagnolo** [comment]
i have fixed it was a glb model's problem now it work thank you

**Comment by MarlonJD** [comment]
Happy to hear that
