### ISSUE TITLE
Unable to build - gradle version

### ISSUE THREAD

**Issue by nebis-software** [MarlonJD/babylonjs_viewer#15]
Hi,
   newbie here! I am trying to build a simple example, but it says:

```
[   +8 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
[        ] The following dependencies do not satisfy the required version:
[        ] project ':flutter_gl' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61

```
but the flutter_gl plugin should be alreay updated... did i miss some setting?
Thanks!!

**Comment by MarlonJD** [comment]
Can you share your android/build.gradle?
there is no dependency of flutter_gl for this project

**Comment by nebis-software** [comment]
Sorry my bad, it was a leftover from a previous unrelated test.
