### ISSUE TITLE
Other functions beside viewer

### ISSUE THREAD

**Issue by jamesleetu** [MarlonJD/babylonjs_viewer#9]
Thanks for your great effort :)

I'm just wondering if there are any more functions beside basic 3D viewer.
ex) Turning on AR when button pressed, changing model viewer's background

Thank you :)

**Comment by MarlonJD** [comment]
Hello, thank you,

Other functions are, animations, events (promises, observables and callbacks), camera settings, scene. All properties is [here](https://github.com/BabylonJS/Babylon.js/blob/master/packages/tools/viewer/src/configuration/configuration.ts). If you need spesific feature, I can think about it to add in future.
Unfortunetly this library (babylonjs viewer) not support AR directly. If you need AR you can visit [this library](https://pub.dev/packages/model_viewer).

**Comment by jamesleetu** [comment]
Thank you for your reply.

Will be greatful if you add more features in future

Wish you the best :)
